### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Christilut**

### CODE REVIEW

**Comment by Glavin001** [comment]
Thanks for the PR! 🎉 

Is there a code snippet which you could provide as well? Or any changes to https://github.com/Glavin001/castv2-plex/blob/master/demo.js which you think is necessary to work properly?

**Review by Glavin001 — COMMENTED** [review]
Thanks for the PR! 🎉 

Is there a code snippet which you could provide as well? Or any changes to https://github.com/Glavin001/castv2-plex/blob/master/demo.js which you think is necessary to work properly?

**Comment by Christilut** [comment]
There's no code change, its just a heads-up that `videoId` is actually the `ratingKey` from Plex. That cost part of a day of trial and error :)

**Comment by Glavin001** [comment]
Thank you for contributing!

**Pull request merged**
